version: '3.3'

services:
    atcoder:
        build: 
            context: ./
            dockerfile: Dockerfile
        container_name: atcoder
        stdin_open: true
        tty: true
        volumes:
            - ../../atcoder:/atcoder
